<a href="https://colab.research.google.com/github/leofanci/ML_works/blob/main/ML2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.) Import the data from CCLE into a new Google Colab file

In [ ]:
import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt
from sklearn import preprocessing
import numpy as np

In [ ]:
drive.mount('/content/gdrive/', force_remount = True)

Mounted at /content/gdrive/


In [ ]:
df = pd.read_csv('gdrive/MyDrive/ML/insurance.csv')
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df.loc[df['sex'] == 'female','sex'] = 1
df.loc[df["sex"] == 'male','sex'] = 0
df.loc[df['smoker'] == 'yes','smoker'] = 1
df.loc[df["smoker"] == 'no','smoker'] = 0
df = pd.concat([df, pd.get_dummies(df.region)], 1)
df

<ipython-input-4-6eb52c1cc261>:5: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  df = pd.concat([df, pd.get_dummies(df.region)], 1)


age sex     bmi  children smoker     region      charges  northeast  \
0      19   1  27.900         0      1  southwest  16884.92400          0   
1      18   0  33.770         1      0  southeast   1725.55230          0   
2      28   0  33.000         3      0  southeast   4449.46200          0   
3      33   0  22.705         0      0  northwest  21984.47061          0   
4      32   0  28.880         0      0  northwest   3866.85520          0   
...   ...  ..     ...       ...    ...        ...          ...        ...   
1333   50   0  30.970         3      0  northwest  10600.54830          0   
1334   18   1  31.920         0      0  northeast   2205.98080          1   
1335   18   1  36.850         0      0  southeast   1629.83350          0   
1336   21   1  25.800         0      0  southwest   2007.94500          0   
1337   61   1  29.070         0      1  northwest  29141.36030          0   

      northwest  southeast  southwest  
0             0          0          1  
1             0          1          0  
2             0          1          0  
3             1          0          0  
4             1          0          0  
...         ...        ...        ...  
1333          1          0          0  
1334          0          0          0  
1335          0          1          0  
1336          0          0          1  
1337          1          0          0  

[1338 rows x 11 columns]

In [ ]:
data = df[['age', 'sex', 'bmi', 'children', 'smoker', 'northeast', 'northwest', 'southeast', 'southwest']]
target = df[['charges']]

In [ ]:
data.head()

age sex     bmi  children smoker  northeast  northwest  southeast  \
0   19   1  27.900         0      1          0          0          0   
1   18   0  33.770         1      0          0          0          1   
2   28   0  33.000         3      0          0          0          1   
3   33   0  22.705         0      0          0          1          0   
4   32   0  28.880         0      0          0          1          0   

   southwest  
0          1  
1          0  
2          0  
3          0  
4          0

In [ ]:
target.head()

charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

# 2.) Split the data into 80/20, in/out sample

In [ ]:
cut = int((len(df) * .8) //1)

In [ ]:
in_data = data[:cut]
out_data = data[cut:]
in_target = target[:cut]
out_target = target[cut:]

# 3.) Normalize the Data

In [ ]:
scaler = preprocessing.StandardScaler().fit(in_data)
in_data_scale = scaler.transform(in_data)
out_data_scale = scaler.transform(out_data)

In [ ]:
in_data

age sex     bmi  children smoker  northeast  northwest  southeast  \
0      19   1  27.900         0      1          0          0          0   
1      18   0  33.770         1      0          0          0          1   
2      28   0  33.000         3      0          0          0          1   
3      33   0  22.705         0      0          0          1          0   
4      32   0  28.880         0      0          0          1          0   
...   ...  ..     ...       ...    ...        ...        ...        ...   
1065   42   1  25.300         1      0          0          0          0   
1066   48   0  37.290         2      0          0          0          1   
1067   39   0  42.655         0      0          1          0          0   
1068   63   0  21.660         1      0          0          1          0   
1069   54   1  31.900         1      0          0          0          1   

      southwest  
0             1  
1             0  
2             0  
3             0  
4             0  
...         ...  
1065          1  
1066          0  
1067          0  
1068          0  
1069          0  

[1070 rows x 9 columns]

In [ ]:
in_data_scale

array([[-1.45390122,  1.02077653, -0.47403991, ..., -0.55791981,
        -0.6155209 ,  1.76504522],
       [-1.52464584, -0.97964634,  0.4911621 , ..., -0.55791981,
         1.6246402 , -0.56655772],
       [-0.81719959, -0.97964634,  0.36455128, ..., -0.55791981,
         1.6246402 , -0.56655772],
       ...,
       [-0.03900872, -0.97964634,  1.95211949, ..., -0.55791981,
        -0.6155209 , -0.56655772],
       [ 1.65886228, -0.97964634, -1.50008089, ...,  1.79237229,
        -0.6155209 , -0.56655772],
       [ 1.02216066,  1.02077653,  0.18367867, ..., -0.55791981,
         1.6246402 , -0.56655772]])

# 4.) Get lambda from Lasso cross validation

In [ ]:
from sklearn.linear_model import LassoCV

In [ ]:
modCV = LassoCV().fit(in_data_scale, in_target)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_coordinate_descent.py:1571: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
a = modCV.alpha_

In [ ]:
a

176.27926602952408

# 5.) Run a lambda regression with that Lambda

In [ ]:
from sklearn.linear_model import Lasso

In [ ]:
model = Lasso(alpha = a).fit(in_data_scale, in_target)

# 6.) Visualize the coefficients 

In [ ]:
model.coef_

array([3528.02573535,    0.        , 1826.25842562,  357.05552225,
       9280.6004751 ,  184.56649395,    0.        ,   -0.        ,
        -65.22282232])

# 7.) Interpret the coefficients

The magnitudes of the coefficients are generally high, however, the coefficient for $age$ is 0. All the variables have a positive relationship with $charges$, yet the variable for the region has a negative association with the target. The most important variable to explain $charges$ seems to be the dummy for smokers.

# 8.) Compare in and out of sample MSE’s

In [ ]:
#mod1.predict("in sample data")
#mod1.predict("out of sample data")

In [ ]:
in_predict = model.predict(np.array(in_data_scale))
in_predict

array([25183.57743363,  3987.44348867,  6851.48155101, ...,
       12026.42881497, 11582.4177949 , 12411.09815309])

In [ ]:
out_predict = model.predict(np.array(out_data_scale))
out_predict

array([32881.60606615, 14650.29903003,  3681.29135194, 12233.12640909,
        9964.71714263,  6226.47101971, 10541.93152711,  2541.49111524,
       28717.05094509, 15785.28364643,   686.64090693,  5699.46027398,
        4829.19870229,  6647.95314975, 14285.58691374, 28790.99469777,
       11911.86934097, 12752.07317137, 16668.53024526,  9515.66333029,
       34813.55175638, 12168.61816581,  5361.37623118, 26835.14528908,
       12700.25319927,  4589.01993162, 36471.1431613 ,  4686.11213302,
       11733.65571191,  5800.6295178 , 27214.42663921, 11617.84876754,
        8285.42551354, 14364.98327445,  7085.71591236, 11913.21929126,
       10270.39230715, 10006.77649692,  4699.98346863,  7295.81068863,
       12960.43492194, 34126.95264754, 32857.19179369,  4844.03606087,
        2584.2264754 , 12891.91109868, 10115.75279595, 29063.13813327,
       31486.86648465,  3431.86141359, 27232.95144572, 12596.89879338,
       37411.34024779,  6250.06341078, 31522.23542949, 12309.72630776,
      

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(in_target, in_predict)

36603129.01103468

In [ ]:
mean_squared_error(out_target, out_predict)

37305075.46630295

The in-sample model has a lower MSE score.